/* option `HEARTBEAT_MAX_PERIOD_DEFAULT' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_HEARTBEAT_MAX_PERIOD_DEFAULT
 .global _KERNEL_OPT_HEARTBEAT_MAX_PERIOD_DEFAULT
 .equiv _KERNEL_OPT_HEARTBEAT_MAX_PERIOD_DEFAULT,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_HEARTBEAT_MAX_PERIOD_DEFAULT\n .global _KERNEL_OPT_HEARTBEAT_MAX_PERIOD_DEFAULT\n .equiv _KERNEL_OPT_HEARTBEAT_MAX_PERIOD_DEFAULT,0x6e074def\n .endif");
#endif
