/* option `SC16IS7XX_SPI_FREQUENCY' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_SC16IS7XX_SPI_FREQUENCY
 .global _KERNEL_OPT_SC16IS7XX_SPI_FREQUENCY
 .equiv _KERNEL_OPT_SC16IS7XX_SPI_FREQUENCY,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_SC16IS7XX_SPI_FREQUENCY\n .global _KERNEL_OPT_SC16IS7XX_SPI_FREQUENCY\n .equiv _KERNEL_OPT_SC16IS7XX_SPI_FREQUENCY,0x6e074def\n .endif");
#endif
