#define	NPCKBPORT	0
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_NPCKBPORT
 .global _KERNEL_OPT_NPCKBPORT
 .equiv _KERNEL_OPT_NPCKBPORT,0x0
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_NPCKBPORT\n .global _KERNEL_OPT_NPCKBPORT\n .equiv _KERNEL_OPT_NPCKBPORT,0x0\n .endif");
#endif
#define	NPCKBPORT_MACHDEP_CNATTACH	0
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_NPCKBPORT_MACHDEP_CNATTACH
 .global _KERNEL_OPT_NPCKBPORT_MACHDEP_CNATTACH
 .equiv _KERNEL_OPT_NPCKBPORT_MACHDEP_CNATTACH,0x0
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_NPCKBPORT_MACHDEP_CNATTACH\n .global _KERNEL_OPT_NPCKBPORT_MACHDEP_CNATTACH\n .equiv _KERNEL_OPT_NPCKBPORT_MACHDEP_CNATTACH,0x0\n .endif");
#endif
