#include <sys/cdefs.h>

#include "opt_config.h"

/*
 * Add either (or both) of
 *
 *	options INCLUDE_CONFIG_FILE
 *	options INCLUDE_JUST_CONFIG
 *
 * to your kernel config file to embed it in the resulting
 * kernel.  The latter option does not include files that are
 * included (recursively) by your config file.  The embedded
 * data be extracted by using the command:
 *
 *	strings netbsd | sed -n 's/^_CFG_//p' | unvis
 */

#ifdef CONFIG_FILE
#if defined(INCLUDE_CONFIG_FILE) || defined(INCLUDE_JUST_CONFIG)

static const char config[] __used =

#ifdef INCLUDE_CONFIG_FILE

"_CFG_### START CONFIG FILE \"GENERIC\"\n"

#endif /* INCLUDE_CONFIG_FILE */

"_CFG_# $NetBSD: GENERIC,v 1.12 2025/08/27 04:47:17 isaki Exp $\n"
"_CFG_#\n"
"_CFG_# GENERIC machine description file\n"
"_CFG_# \n"
"_CFG_# This machine description file is used to generate the default NetBSD\n"
"_CFG_# kernel.  The generic kernel does not include all options, subsystems\n"
"_CFG_# and device drivers, but should be useful for most applications.\n"
"_CFG_#\n"
"_CFG_# The machine description file can be customised for your specific\n"
"_CFG_# machine to reduce the kernel size and improve its performance.\n"
"_CFG_#\n"
"_CFG_# For further information on compiling NetBSD kernels, see the config(8)\n"
"_CFG_# man page.\n"
"_CFG_#\n"
"_CFG_# For further information on hardware support for this architecture, see\n"
"_CFG_# the intro(4) man page.  For further information about kernel options\n"
"_CFG_# for this architecture, see the options(4) man page.  For an explanation\n"
"_CFG_# of each device driver in this file see the section 4 man page for the\n"
"_CFG_# device.\n"
"_CFG_\n"
"_CFG_include \\011\"arch/re86k/conf/std.re86k\"\n"
"_CFG_\n"
"_CFG_options \\011INCLUDE_CONFIG_FILE\\011# embed config file in kernel binary\n"
"_CFG_\n"
"_CFG_#ident \\011\\011\"GENERIC-$Revision: 1.12 $\"\n"
"_CFG_\n"
"_CFG_makeoptions\\011COPTS=\"-O2 -fno-reorder-blocks\"\\011# see share/mk/sys.mk\n"
"_CFG_\n"
"_CFG_# reserve symbol space and copy the symbol table into it.  Needed\n"
"_CFG_# because Qemu does not load the symbol table when loading the\n"
"_CFG_# kernel.\n"
"_CFG_makeoptions     COPY_SYMTAB=1\n"
"_CFG_\n"
"_CFG_# CPUs this kernel supports\n"
"_CFG_options \\011M68030\n"
"_CFG_options \\011M68040\n"
"_CFG_\n"
"_CFG_maxusers\\01116\n"
"_CFG_\n"
"_CFG_# Needed on m68040 boards to emulate some missing FP instructions\n"
"_CFG_options \\011FPSP\n"
"_CFG_\n"
"_CFG_options \\011DDB\n"
"_CFG_options \\011DIAGNOSTIC\n"
"_CFG_#options \\011LOCKDEBUG\n"
"_CFG_#options \\011DEBUG\n"
"_CFG_\n"
"_CFG_#options \\011SYSVSHM\n"
"_CFG_options \\011KTRACE\n"
"_CFG_\n"
"_CFG_options \\011USERCONF\\011# userconf(4) support\n"
"_CFG_#options \\011PIPE_SOCKETPAIR\\011# smaller, but slower pipe(2)\n"
"_CFG_options \\011SYSCTL_INCLUDE_DESCR\\011# Include sysctl descriptions in kernel\n"
"_CFG_\n"
"_CFG_# Alternate buffer queue strategies for better responsiveness under high\n"
"_CFG_# disk I/O load.\n"
"_CFG_#options \\011BUFQ_READPRIO\n"
"_CFG_#options \\011BUFQ_PRIOCSCAN\n"
"_CFG_\n"
"_CFG_file-system \\011FFS\n"
"_CFG_file-system \\011NFS\n"
"_CFG_file-system \\011KERNFS\n"
"_CFG_file-system \\011PROCFS\n"
"_CFG_#file-system \\011MFS\n"
"_CFG_file-system \\011CD9660\n"
"_CFG_file-system\\011MSDOSFS\n"
"_CFG_#file-system\\011UNION\n"
"_CFG_file-system\\011PTYFS\\011\\011# /dev/pts/N support\n"
"_CFG_file-system\\011TMPFS\\011\\011# Efficient memory file-system\n"
"_CFG_#file-system\\011UDF\\011\\011# experimental - OSTA UDF CD/DVD file-system\n"
"_CFG_file-system\\011NULLFS\\011\\011# loopback file system\n"
"_CFG_file-system\\011PUFFS\\011\\011# Userspace file systems (e.g. ntfs-3g & sshfs)\n"
"_CFG_pseudo-device\\011putter\\011\\011# for puffs and pud\n"
"_CFG_\n"
"_CFG_# File system options\n"
"_CFG_#options \\011FFS_EI\\011\\011# FFS Endian Independent support\n"
"_CFG_options \\011FFS_NO_SNAPSHOT\\011# No FFS snapshot support\n"
"_CFG_#options \\011UFS_DIRHASH\\011# UFS Large Directory Hashing\n"
"_CFG_#options \\011UFS_EXTATTR\\011# Extended attribute support for UFS1\n"
"_CFG_options \\011WAPBL\\011\\011# File system journaling support\n"
"_CFG_options \\011NFSSERVER\\011# Network File System server\n"
"_CFG_\n"
"_CFG_# Networking options\n"
"_CFG_options \\011INET\n"
"_CFG_options \\011INET6\\011\\011# IPV6\n"
"_CFG_#options \\011IPSEC\\011\\011# IP security\n"
"_CFG_#options \\011IPSEC_DEBUG\\011# debug for IP security\n"
"_CFG_#options \\011GATEWAY\\011\\011# IP packet forwarding\n"
"_CFG_#options \\011TCP_DEBUG\\011# Record last TCP_NDEBUG packets with SO_DEBUG\n"
"_CFG_\n"
"_CFG_#options \\011ALTQ\\011\\011# Manipulate network interfaces' output queues\n"
"_CFG_#options \\011ALTQ_BLUE\\011# Stochastic Fair Blue\n"
"_CFG_#options \\011ALTQ_CBQ\\011# Class-Based Queueing\n"
"_CFG_#options \\011ALTQ_CDNR\\011# Diffserv Traffic Conditioner\n"
"_CFG_#options \\011ALTQ_FIFOQ\\011# First-In First-Out Queue\n"
"_CFG_#options \\011ALTQ_FLOWVALVE\\011# RED/flow-valve (red-penalty-box)\n"
"_CFG_#options \\011ALTQ_HFSC\\011# Hierarchical Fair Service Curve\n"
"_CFG_#options \\011ALTQ_LOCALQ\\011# Local queueing discipline\n"
"_CFG_#options \\011ALTQ_PRIQ\\011# Priority Queueing\n"
"_CFG_#options \\011ALTQ_RED\\011# Random Early Detection\n"
"_CFG_#options \\011ALTQ_RIO\\011# RED with IN/OUT\n"
"_CFG_#options \\011ALTQ_WFQ\\011# Weighted Fair Queueing\n"
"_CFG_\n"
"_CFG_options \\011COMPAT_AOUT_M68K\\011# compatibility with NetBSD/m68k a.out\n"
"_CFG_include \\011\"conf/compat_netbsd09.config\"\n"
"_CFG_#options \\011COMPAT_SUNOS\n"
"_CFG_#options \\011COMPAT_M68K4K\\011# compatibility with NetBSD/m68k4k binaries\n"
"_CFG_#options \\011COMPAT_LINUX\\011# compatibility with Linux/m68k binaries\n"
"_CFG_#options \\011COMPAT_OSSAUDIO\\011# compatibility with Linux/m68k binaries\n"
"_CFG_\n"
"_CFG_# Shared memory options\n"
"_CFG_options \\011SYSVMSG\\011\\011# System V-like message queues\n"
"_CFG_options \\011SYSVSEM\\011\\011# System V-like semaphores\n"
"_CFG_options \\011SYSVSHM\\011\\011# System V-like memory sharing\n"
"_CFG_\n"
"_CFG_## force NFS root and swap\n"
"_CFG_#config\\011netbsd\\011\\011root on ? type nfs\n"
"_CFG_## \"generic\" boot (put root on boot device)\n"
"_CFG_config netbsd\\011\\011root on ? type ?\n"
"_CFG_\n"
"_CFG_# Which protocol to use when booting over NFS\n"
"_CFG_options \\011NFS_BOOT_DHCP\\011\\011# Diskless client w/ dhcp\n"
"_CFG_options \\011NFS_BOOT_BOOTP\\011\\011# Diskless client w/ bootp\n"
"_CFG_options \\011NFS_BOOT_BOOTPARAM\\011# Diskless client w/ bootparamd\n"
"_CFG_\n"
"_CFG_#\n"
"_CFG_# accept filters\n"
"_CFG_pseudo-device   accf_data\\011\\011# \"dataready\" accept filter\n"
"_CFG_pseudo-device   accf_http\\011\\011# \"httpready\" accept filter\n"
"_CFG_\n"
"_CFG_pseudo-device\\011sl\n"
"_CFG_pseudo-device\\011ppp \n"
"_CFG_#pseudo-device\\011pppoe\\011\\011\\011# PPP over Ethernet (RFC 2516)\n"
"_CFG_pseudo-device\\011loop\n"
"_CFG_pseudo-device\\011bpfilter\n"
"_CFG_#pseudo-device\\011carp\\011\\011\\011# Common Address Redundancy Protocol\n"
"_CFG_pseudo-device\\011gif\\011\\011\\011# IPv[46] over IPv[46] tunnel (RFC1933)\n"
"_CFG_#pseudo-device\\011faith\\011\\011\\011# IPv[46] tcp relay translation i/f\n"
"_CFG_pseudo-device\\011stf\\011\\011\\011# 6to4 IPv6 over IPv4 encapsulation\n"
"_CFG_#pseudo-device\\011vlan\\011\\011\\011# IEEE 802.1q encapsulation\n"
"_CFG_#pseudo-device\\011bridge\\011\\011\\011# simple inter-network bridging\n"
"_CFG_#pseudo-device\\011vether\\011\\011\\011# Virtual Ethernet for bridge\n"
"_CFG_#pseudo-device\\011agr\\011\\011\\011# IEEE 802.3ad link aggregation\n"
"_CFG_pseudo-device\\011pty\\011\\011\\011# pseudo-terminals\n"
"_CFG_#pseudo-device\\011cgd\\011\\011\\011# cryptographic disk devices\n"
"_CFG_pseudo-device\\011vnd \n"
"_CFG_#options \\011VND_COMPRESSION\\011\\011# compressed vnd(4)\n"
"_CFG_pseudo-device\\011fss\\011\\011\\011# file system snapshot device\n"
"_CFG_pseudo-device\\011clockctl\\011\\011# user control of clock subsystem\n"
"_CFG_pseudo-device\\011ksyms\\011\\011\\011# /dev/ksyms\n"
"_CFG_#pseudo-device\\011npf\\011\\011\\011# NPF packet filter\n"
"_CFG_pseudo-device \\011swwdog\\011\\011\\011# software watchdog timer -- swwdog(4)\n"
"_CFG_pseudo-device\\011drvctl\\011\\011\\011# user control of drive subsystem\n"
"_CFG_\n"
"_CFG_# crypto pseudo-devices\n"
"_CFG_pseudo-device\\011crypto\\011\\011\\011# /dev/crypto device\n"
"_CFG_pseudo-device\\011swcrypto\\011\\011# software crypto implementation\n"
"_CFG_\n"
"_CFG_# random number generator pseudo-device\n"
"_CFG_#options \\011RND_COM\\011\\011\\011# use \"com\" randomness as well (BROKEN)\n"
"_CFG_\n"
"_CFG_# Veriexec\n"
"_CFG_# include \"dev/veriexec.config\"\n"
"_CFG_\n"
"_CFG_mainbus0\\011at root\n"
"_CFG_\n"
"_CFG_# Goldfish virtual devices\n"
"_CFG_#gfpic*\\011\\011at mainbus? addr ?\\011# interrupt controller\n"
"_CFG_#gftty*\\011\\011at mainbus? addr ?\\011# console terminal\n"
"_CFG_#gfrtc*\\011\\011at mainbus? addr ?\\011# real-time clock / timer\n"
"_CFG_\n"
"_CFG_# Qemu Virtual System Controller\n"
"_CFG_#virtctrl*\\011at mainbus? addr ?\n"
"_CFG_\n"
"_CFG_# VirtIO devices\n"
"_CFG_#virtio*\\011\\011at mainbus? addr ?\\011# VirtIO nexus\n"
"_CFG_\n"
"_CFG_\n"
"_CFG_# SCSI devices\n"
"_CFG_#scsibus* at scsi?\n"
"_CFG_#sd*\\011\\011at scsibus? target ? lun ?\\011# SCSI disks\n"
"_CFG_#st*\\011\\011at scsibus? target ? lun ?\\011# SCSI tapes\n"
"_CFG_#cd*\\011\\011at scsibus? target ? lun ?\\011# SCSI CD-ROMs\n"
"_CFG_#ch*\\011\\011at scsibus? target ? lun ?\\011# SCSI changer devices\n"
"_CFG_#ss*\\011\\011at scsibus? target ? lun ?\\011# SCSI scanners\n"
"_CFG_#ses*\\011\\011at scsibus? target ? lun ?\\011# SCSI SES/SAF-TE devices\n"
"_CFG_#uk*\\011\\011at scsibus? target ? lun ?\\011# unknown SCSI\n"
"_CFG_\n"
"_CFG_# Pull in optional local configuration - always at end\n"
"_CFG_cinclude\\011\"arch/re86k/conf/GENERIC.local\"\n"
"_CFG_\n"
"_CFG_# RE86K Hardware devices\n"
"_CFG_duart*\\011at mainbus? addr 0x00a00000\\011# MC68681 DUART (serial console)\n"
"_CFG_\n"
"_CFG_# TODO: Add RTC and Ethernet when ready\n"
"_CFG_#rtc*\\011\\011at mainbus? addr 0x00a00020\\011# DS12887 RTC\n"
"_CFG_#cs*\\011\\011at mainbus? addr 0x00a10000\\011# CS8900A Ethernet\n"
#ifdef INCLUDE_CONFIG_FILE

"_CFG_### END CONFIG FILE \"GENERIC\"\n"
"_CFG_### (included from \"arch/re86k/conf/std.re86k\")\n"
"_CFG_###> #\\011$NetBSD: std.re86k,v 1.2 2024/01/02 16:48:01 thorpej Exp $\n"
"_CFG_###> #\n"
"_CFG_###> # Options/devices that all re86ks should have\n"
"_CFG_###> #\n"
"_CFG_###> \n"
"_CFG_###> machine re86k m68k\n"
"_CFG_###> include\\011\\011\"conf/std\"\\011\\011\\011# MI standard options\n"
"_CFG_###> include\\011\\011\"arch/m68k/conf/std.m68k\"\\011# m68k standard options\n"
"_CFG_###> \n"
"_CFG_###> options \\011EXEC_AOUT\\011# support for exec'ing a.out\n"
"_CFG_### (end include \"arch/re86k/conf/std.re86k\")\n"
"_CFG_### (included from \"conf/std\")\n"
"_CFG_###> # $NetBSD: std,v 1.24 2024/03/26 10:56:34 riastradh Exp $\n"
"_CFG_###> #\n"
"_CFG_###> # standard MI 'options'\n"
"_CFG_###> #\n"
"_CFG_###> # this file is for options which can't be off-by-default for some reasons.\n"
"_CFG_###> # \"it's commonly used\" is NOT a good reason to enable options here.\n"
"_CFG_###> \n"
"_CFG_###> #\n"
"_CFG_###> # Always include \"kern\" attribute (module).  Other attributes don't need to\n"
"_CFG_###> # depend on \"kern\".\n"
"_CFG_###> #\n"
"_CFG_###> select\\011kern\n"
"_CFG_###> \n"
"_CFG_###> # Always include the \"vfs\" attribute (module).  Although all of the\n"
"_CFG_###> # ufs/xxx file systems depend on the vfs attribute, it is not required\n"
"_CFG_###> # that any file system actually be built-in to the kernel.  (At least\n"
"_CFG_###> # on some architectures, file system modules can be loaded at boot\n"
"_CFG_###> # time.)\n"
"_CFG_###> \n"
"_CFG_###> select vfs\n"
"_CFG_###> \n"
"_CFG_###> select\\011net\\011\\011# XXX Clean up dependency\n"
"_CFG_###> \n"
"_CFG_###> # the following options are on-by-default to keep\n"
"_CFG_###> # kernel config file compatibility.\n"
"_CFG_###> options\\011VMSWAP\\011\\011# Swap device/file support\n"
"_CFG_###> options\\011BUFQ_FCFS\\011# First-come First-serve strategy\n"
"_CFG_###> options\\011BUFQ_DISKSORT\\011# Traditional min seek sort strategy\n"
"_CFG_###> options\\011RFC2292\\011\\011# Previous version of Adv. Sockets API for IPv6 \n"
"_CFG_###> options\\011PTRACE\\011\\011# Include ptrace(2) syscall\n"
"_CFG_###> options\\011PTRACE_HOOKS\\011# Include ptrace hooks\n"
"_CFG_###> options\\011COREDUMP\\011# allow processes to coredump.\n"
"_CFG_###> options\\011AIO\\011\\011# POSIX asynchronous I/O\n"
"_CFG_###> options\\011MQUEUE\\011\\011# POSIX message queues\n"
"_CFG_###> \n"
"_CFG_###> # Common compatibility functions. They happen to be needed even when\n"
"_CFG_###> # no compatibility option is explicitly enabled.\n"
"_CFG_###> #\n"
"_CFG_###> options        COMPAT_UTILS\n"
"_CFG_###> \n"
"_CFG_###> #\n"
"_CFG_###> # Security model.\n"
"_CFG_###> #\n"
"_CFG_###> options\\011secmodel_bsd44\\011# Traditional 4.4BSD security model\n"
"_CFG_###> \n"
"_CFG_###> #\n"
"_CFG_###> # Scheduling algorithm\n"
"_CFG_###> #\n"
"_CFG_###> options\\011SCHED_4BSD\n"
"_CFG_###> \n"
"_CFG_###> pseudo-device\\011cpuctl\n"
"_CFG_###> \n"
"_CFG_###> #\n"
"_CFG_###> # /dev/random and /dev/urandom interfaces.\n"
"_CFG_###> #\n"
"_CFG_###> # This could be taken out of conf/std now that the entropy pool and\n"
"_CFG_###> # kernel random number generation API is part of kern proper --\n"
"_CFG_###> # provided that some care is taken in ensuring that we copy & paste\n"
"_CFG_###> # this line in essentially every kernel config, because many\n"
"_CFG_###> # applications, even embedded ones, will likely rely in some way or\n"
"_CFG_###> # other on reading from /dev/urandom.\n"
"_CFG_###> #\n"
"_CFG_###> pseudo-device\\011rnd\n"
"_CFG_### (end include \"conf/std\")\n"
"_CFG_### (included from \"arch/m68k/conf/std.m68k\")\n"
"_CFG_###> # $NetBSD: std.m68k,v 1.2 2021/06/04 10:46:11 martin Exp $\n"
"_CFG_###> #\n"
"_CFG_###> # standard, required NetBSD/m68k options\n"
"_CFG_###> \n"
"_CFG_###> options \\011EXEC_ELF32\\011\\011# exec ELF binaries\n"
"_CFG_###> options \\011EXEC_SCRIPT\\011\\011# exec #! scripts\n"
"_CFG_###> \n"
"_CFG_###> options \\011CPU_IN_CKSUM\\011\\011# use MD optimized cpu_in_cksum()\n"
"_CFG_###> \n"
"_CFG_###> options\\011\\011VMSWAP_DEFAULT_PLAINTEXT\\011# do not encrypt swap by\n"
"_CFG_###> \\011\\011\\011\\011\\011# default (slow cpu)\n"
"_CFG_### (end include \"arch/m68k/conf/std.m68k\")\n"
"_CFG_### (included from \"conf/compat_netbsd09.config\")\n"
"_CFG_###> #\\011$NetBSD: compat_netbsd09.config,v 1.2 2018/01/15 07:20:10 mrg Exp $\n"
"_CFG_###> \n"
"_CFG_###> # Common fragment for all NetBSD targets wanting NetBSD 0.9 and newer\n"
"_CFG_###> # compatibility support.\n"
"_CFG_###> #\n"
"_CFG_###> # Note that COMPAT_09 implies all newer COMPAT_XX options.\n"
"_CFG_###> \n"
"_CFG_###> include        \"conf/compat_netbsd.config\"\n"
"_CFG_###> options \\011COMPAT_09\\011# NetBSD 0.9 and beyond.\n"
"_CFG_### (end include \"conf/compat_netbsd09.config\")\n"
"_CFG_### (included from \"conf/compat_netbsd.config\")\n"
"_CFG_###> # $NetBSD: compat_netbsd.config,v 1.1 2017/09/14 07:58:44 mrg Exp $\n"
"_CFG_###> \n"
"_CFG_###> # Traditional NetBSD options enabled for most kernels.\n"
"_CFG_###> \n"
"_CFG_###> options \\011COMPAT_43\\011# 4.3BSD system interfaces\n"
"_CFG_###> options \\011COMPAT_44\\011# 4.4BSD system interfaces\n"
"_CFG_###> options \\011COMPAT_BSDPTY\\011# /dev/[pt]ty?? ptys.\n"
"_CFG_### (end include \"conf/compat_netbsd.config\")\n"
#endif /* INCLUDE_CONFIG_FILE */
;
#endif /* INCLUDE_CONFIG_FILE || INCLUDE_JUST_CONFIG */
#endif /* CONFIG_FILE */
