/* option `PCKBD_CNATTACH_MAY_FAIL' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL
 .global _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL
 .equiv _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL\n .global _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL\n .equiv _KERNEL_OPT_PCKBD_CNATTACH_MAY_FAIL,0x6e074def\n .endif");
#endif
