/* option `PMS_DISABLE_POWERHOOK' is obsolete */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PMS_DISABLE_POWERHOOK
 .global _KERNEL_OPT_PMS_DISABLE_POWERHOOK
 .equiv _KERNEL_OPT_PMS_DISABLE_POWERHOOK,0xdeadbeef
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PMS_DISABLE_POWERHOOK\n .global _KERNEL_OPT_PMS_DISABLE_POWERHOOK\n .equiv _KERNEL_OPT_PMS_DISABLE_POWERHOOK,0xdeadbeef\n .endif");
#endif
/* option `PMS_SYNAPTICS_TOUCHPAD' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PMS_SYNAPTICS_TOUCHPAD
 .global _KERNEL_OPT_PMS_SYNAPTICS_TOUCHPAD
 .equiv _KERNEL_OPT_PMS_SYNAPTICS_TOUCHPAD,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PMS_SYNAPTICS_TOUCHPAD\n .global _KERNEL_OPT_PMS_SYNAPTICS_TOUCHPAD\n .equiv _KERNEL_OPT_PMS_SYNAPTICS_TOUCHPAD,0x6e074def\n .endif");
#endif
/* option `PMS_ELANTECH_TOUCHPAD' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PMS_ELANTECH_TOUCHPAD
 .global _KERNEL_OPT_PMS_ELANTECH_TOUCHPAD
 .equiv _KERNEL_OPT_PMS_ELANTECH_TOUCHPAD,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PMS_ELANTECH_TOUCHPAD\n .global _KERNEL_OPT_PMS_ELANTECH_TOUCHPAD\n .equiv _KERNEL_OPT_PMS_ELANTECH_TOUCHPAD,0x6e074def\n .endif");
#endif
/* option `PMS_ALPS_TOUCHPAD' not defined */
#ifdef _LOCORE
 .ifndef _KERNEL_OPT_PMS_ALPS_TOUCHPAD
 .global _KERNEL_OPT_PMS_ALPS_TOUCHPAD
 .equiv _KERNEL_OPT_PMS_ALPS_TOUCHPAD,0x6e074def
 .endif
#else
__asm(" .ifndef _KERNEL_OPT_PMS_ALPS_TOUCHPAD\n .global _KERNEL_OPT_PMS_ALPS_TOUCHPAD\n .equiv _KERNEL_OPT_PMS_ALPS_TOUCHPAD,0x6e074def\n .endif");
#endif
